// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package viettel.statistic_smpp.dto;

/**
 * Protobuf type {@code tutorial.Body}
 */
public final class Body extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Body)
    BodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Body.newBuilder() to construct.
  private Body(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Body() {
    payload_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Body();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Body(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              payload_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            payload_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        payload_ = payload_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return viettel.statistic_smpp.dto.Event.internal_static_tutorial_Body_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return viettel.statistic_smpp.dto.Event.internal_static_tutorial_Body_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            viettel.statistic_smpp.dto.Body.class, viettel.statistic_smpp.dto.Body.Builder.class);
  }

  public static final int PAYLOAD_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList payload_;
  /**
   * <code>repeated string payload = 1;</code>
   * @return A list containing the payload.
   */
  public com.google.protobuf.ProtocolStringList
      getPayloadList() {
    return payload_;
  }
  /**
   * <code>repeated string payload = 1;</code>
   * @return The count of payload.
   */
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <code>repeated string payload = 1;</code>
   * @param index The index of the element to return.
   * @return The payload at the given index.
   */
  public java.lang.String getPayload(int index) {
    return payload_.get(index);
  }
  /**
   * <code>repeated string payload = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the payload at the given index.
   */
  public com.google.protobuf.ByteString
      getPayloadBytes(int index) {
    return payload_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < payload_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, payload_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < payload_.size(); i++) {
        dataSize += computeStringSizeNoTag(payload_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPayloadList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof viettel.statistic_smpp.dto.Body)) {
      return super.equals(obj);
    }
    viettel.statistic_smpp.dto.Body other = (viettel.statistic_smpp.dto.Body) obj;

    if (!getPayloadList()
        .equals(other.getPayloadList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static viettel.statistic_smpp.dto.Body parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static viettel.statistic_smpp.dto.Body parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static viettel.statistic_smpp.dto.Body parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static viettel.statistic_smpp.dto.Body parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(viettel.statistic_smpp.dto.Body prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.Body}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Body)
      viettel.statistic_smpp.dto.BodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return viettel.statistic_smpp.dto.Event.internal_static_tutorial_Body_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return viettel.statistic_smpp.dto.Event.internal_static_tutorial_Body_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              viettel.statistic_smpp.dto.Body.class, viettel.statistic_smpp.dto.Body.Builder.class);
    }

    // Construct using viettel.statistic_smpp.dto.Body.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      payload_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return viettel.statistic_smpp.dto.Event.internal_static_tutorial_Body_descriptor;
    }

    @java.lang.Override
    public viettel.statistic_smpp.dto.Body getDefaultInstanceForType() {
      return viettel.statistic_smpp.dto.Body.getDefaultInstance();
    }

    @java.lang.Override
    public viettel.statistic_smpp.dto.Body build() {
      viettel.statistic_smpp.dto.Body result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public viettel.statistic_smpp.dto.Body buildPartial() {
      viettel.statistic_smpp.dto.Body result = new viettel.statistic_smpp.dto.Body(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        payload_ = payload_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.payload_ = payload_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof viettel.statistic_smpp.dto.Body) {
        return mergeFrom((viettel.statistic_smpp.dto.Body)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(viettel.statistic_smpp.dto.Body other) {
      if (other == viettel.statistic_smpp.dto.Body.getDefaultInstance()) return this;
      if (!other.payload_.isEmpty()) {
        if (payload_.isEmpty()) {
          payload_ = other.payload_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePayloadIsMutable();
          payload_.addAll(other.payload_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      viettel.statistic_smpp.dto.Body parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (viettel.statistic_smpp.dto.Body) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList payload_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        payload_ = new com.google.protobuf.LazyStringArrayList(payload_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @return A list containing the payload.
     */
    public com.google.protobuf.ProtocolStringList
        getPayloadList() {
      return payload_.getUnmodifiableView();
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @return The count of payload.
     */
    public int getPayloadCount() {
      return payload_.size();
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param index The index of the element to return.
     * @return The payload at the given index.
     */
    public java.lang.String getPayload(int index) {
      return payload_.get(index);
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the payload at the given index.
     */
    public com.google.protobuf.ByteString
        getPayloadBytes(int index) {
      return payload_.getByteString(index);
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param index The index to set the value at.
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param value The payload to add.
     * @return This builder for chaining.
     */
    public Builder addPayload(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param values The payload to add.
     * @return This builder for chaining.
     */
    public Builder addAllPayload(
        java.lang.Iterable<java.lang.String> values) {
      ensurePayloadIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, payload_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      payload_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string payload = 1;</code>
     * @param value The bytes of the payload to add.
     * @return This builder for chaining.
     */
    public Builder addPayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePayloadIsMutable();
      payload_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.Body)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Body)
  private static final viettel.statistic_smpp.dto.Body DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new viettel.statistic_smpp.dto.Body();
  }

  public static viettel.statistic_smpp.dto.Body getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Body>
      PARSER = new com.google.protobuf.AbstractParser<Body>() {
    @java.lang.Override
    public Body parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Body(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Body> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Body> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public viettel.statistic_smpp.dto.Body getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

