// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package viettel.statistic_smpp.dto;

public interface BodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Body)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string payload = 1;</code>
   * @return A list containing the payload.
   */
  java.util.List<java.lang.String>
      getPayloadList();
  /**
   * <code>repeated string payload = 1;</code>
   * @return The count of payload.
   */
  int getPayloadCount();
  /**
   * <code>repeated string payload = 1;</code>
   * @param index The index of the element to return.
   * @return The payload at the given index.
   */
  java.lang.String getPayload(int index);
  /**
   * <code>repeated string payload = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the payload at the given index.
   */
  com.google.protobuf.ByteString
      getPayloadBytes(int index);
}
