// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package viettel.statistic_smpp.dto;

public interface HeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Header)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string requestCommand = 1;</code>
   * @return Whether the requestCommand field is set.
   */
  boolean hasRequestCommand();
  /**
   * <code>optional string requestCommand = 1;</code>
   * @return The requestCommand.
   */
  java.lang.String getRequestCommand();
  /**
   * <code>optional string requestCommand = 1;</code>
   * @return The bytes for requestCommand.
   */
  com.google.protobuf.ByteString
      getRequestCommandBytes();

  /**
   * <code>optional string cpId = 2;</code>
   * @return Whether the cpId field is set.
   */
  boolean hasCpId();
  /**
   * <code>optional string cpId = 2;</code>
   * @return The cpId.
   */
  java.lang.String getCpId();
  /**
   * <code>optional string cpId = 2;</code>
   * @return The bytes for cpId.
   */
  com.google.protobuf.ByteString
      getCpIdBytes();
}
