// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package viettel.statistic_smpp.dto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .tutorial.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <code>optional .tutorial.Header header = 1;</code>
   * @return The header.
   */
  viettel.statistic_smpp.dto.Header getHeader();
  /**
   * <code>optional .tutorial.Header header = 1;</code>
   */
  viettel.statistic_smpp.dto.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>optional .tutorial.Body body = 2;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>optional .tutorial.Body body = 2;</code>
   * @return The body.
   */
  viettel.statistic_smpp.dto.Body getBody();
  /**
   * <code>optional .tutorial.Body body = 2;</code>
   */
  viettel.statistic_smpp.dto.BodyOrBuilder getBodyOrBuilder();
}
